"""simconnect_native — 原生 ctypes SimConnect 库（零外部依赖）。"""
from __future__ import annotations

from ctypes import POINTER
from ctypes.wintypes import DWORD, HANDLE

from .client import SimConnect
from .errors import SimConnectError, SimConnectTimeoutError, check_hresult
from .constants import (
    EXCEPTION_NAMES,
    HRESULT_NAMES,
    MSFS_EVENTS,
    SIMCONNECT_DATATYPE_INVALID,
    SIMCONNECT_DATATYPE_INT32,
    SIMCONNECT_DATATYPE_INT64,
    SIMCONNECT_DATATYPE_FLOAT32,
    SIMCONNECT_DATATYPE_FLOAT64,
    SIMCONNECT_DATATYPE_FLOAT64_INT,
    SIMCONNECT_DATATYPE_STRINGV,
    SIMCONNECT_DATA_REQUEST_FLAG_DEFAULT,
    SIMCONNECT_EVENT_FLAG_GROUPID_IS_PRIORITY,
    SIMCONNECT_GROUP_PRIORITY_HIGHEST,
    SIMCONNECT_OBJECT_ID_USER,
    SIMCONNECT_PERIOD_NEVER,
    SIMCONNECT_PERIOD_ONCE,
    SIMCONNECT_PERIOD_SECOND,
    SIMCONNECT_PERIOD_SIM_FRAME,
    SIMCONNECT_PERIOD_VISUAL_FRAME,
    SIMCONNECT_RECV_ID_CLIENT_DATA,
    SIMCONNECT_RECV_ID_EVENT,
    SIMCONNECT_RECV_ID_EVENT_MULTIPLAYER_CLIENT_STARTED,
    SIMCONNECT_RECV_ID_EVENT_MULTIPLAYER_SERVER_STARTED,
    SIMCONNECT_RECV_ID_EVENT_MULTIPLAYER_SESSION_ENDED,
    SIMCONNECT_RECV_ID_EVENT_OBJECT_ADDREMOVE,
    SIMCONNECT_RECV_ID_EVENT_FILENAME,
    SIMCONNECT_RECV_ID_EVENT_FRAME,
    SIMCONNECT_RECV_ID_EVENT_RACE_END,
    SIMCONNECT_RECV_ID_EVENT_RACE_LAP,
    SIMCONNECT_RECV_ID_EVENT_WEATHER_MODE,
    SIMCONNECT_RECV_ID_EXCEPTION,
    SIMCONNECT_RECV_ID_NULL,
    SIMCONNECT_RECV_ID_OPEN,
    SIMCONNECT_RECV_ID_QUIT,
    SIMCONNECT_RECV_ID_SIMOBJECT_DATA,
    SIMCONNECT_RECV_ID_SIMOBJECT_DATA_BYTYPE,
    SIMCONNECT_RECV_ID_SYSTEM_STATE,
    SIMCONNECT_RECV_ID_WEATHER_OBSERVATION,
    SIMCONNECT_SIMOBJECT_TYPE_AIRCRAFT,
    SIMCONNECT_SIMOBJECT_TYPE_ALL,
    SIMCONNECT_SIMOBJECT_TYPE_USER,
    SIMCONNECT_UNUSED,
)
from .dll import (
    bundled_simconnect_dll,
    describe_simconnect_dll_path,
    find_simconnect_dll,
    is_untrusted_simconnect_dll,
)
from .parsing import read_data as _read_data
from .structures import (
    EXCEPTION_MSG,
    FULL_SIMOBJECT_DATA,
    SIMCONNECT_RECV,
    SIMOBJECT_DATA_HEADER,
    SIMOBJECT_DATA_HEADER_SIZE,
    SIMOBJECT_DATA_PAYLOAD_OFFSET,
)

__version__ = "0.5.2"

__all__ = [
    "SIMCONNECT_UNUSED",
    "SIMCONNECT_OBJECT_ID_USER",
    "SIMCONNECT_DATATYPE_INVALID",
    "SIMCONNECT_DATATYPE_FLOAT64",
    "SIMCONNECT_DATATYPE_FLOAT32",
    "SIMCONNECT_DATATYPE_INT32",
    "SIMCONNECT_DATATYPE_INT64",
    "SIMCONNECT_DATATYPE_STRINGV",
    "SIMCONNECT_DATA_REQUEST_FLAG_DEFAULT",
    "SIMCONNECT_EVENT_FLAG_GROUPID_IS_PRIORITY",
    "SIMCONNECT_GROUP_PRIORITY_HIGHEST",
    "SIMCONNECT_SIMOBJECT_TYPE_USER",
    "SIMCONNECT_SIMOBJECT_TYPE_ALL",
    "SIMCONNECT_SIMOBJECT_TYPE_AIRCRAFT",
    "SIMCONNECT_PERIOD_NEVER",
    "SIMCONNECT_PERIOD_ONCE",
    "SIMCONNECT_PERIOD_VISUAL_FRAME",
    "SIMCONNECT_PERIOD_SIM_FRAME",
    "SIMCONNECT_PERIOD_SECOND",
    "SIMCONNECT_RECV_ID_NULL",
    "SIMCONNECT_RECV_ID_EXCEPTION",
    "SIMCONNECT_RECV_ID_OPEN",
    "SIMCONNECT_RECV_ID_QUIT",
    "SIMCONNECT_RECV_ID_EVENT",
    "SIMCONNECT_RECV_ID_SIMOBJECT_DATA",
    "SIMCONNECT_RECV_ID_SIMOBJECT_DATA_BYTYPE",
    "EXCEPTION_NAMES",
    "SIMCONNECT_RECV",
    "SIMOBJECT_DATA_HEADER",
    "SIMOBJECT_DATA_HEADER_SIZE",
    "SIMOBJECT_DATA_PAYLOAD_OFFSET",
    "FULL_SIMOBJECT_DATA",
    "EXCEPTION_MSG",
    "MSFS_EVENTS",
    "find_simconnect_dll",
    "bundled_simconnect_dll",
    "describe_simconnect_dll_path",
    "is_untrusted_simconnect_dll",
    "HRESULT_NAMES",
    "SimConnectError",
    "SimConnectTimeoutError",
    "check_hresult",
    "SimConnect",
    "read_data_value",
    "__version__",
    "POINTER",
    "DWORD",
    "HANDLE",
]


def read_data_value(pData, datatype: int = SIMCONNECT_DATATYPE_FLOAT64_INT):
    """从 dispatch 回调的 pData 中读取指定类型的数据。"""
    return _read_data(pData, datatype)
