"""SimConnect SDK constants and lookup tables."""
from ctypes import c_ulong
from ctypes.wintypes import DWORD

SIMCONNECT_UNUSED = DWORD(0xFFFFFFFF)
SIMCONNECT_OBJECT_ID_USER = DWORD(0)

# SIMCONNECT_DATATYPE（与 MSFS SDK SimConnect.h 枚举一致）
SIMCONNECT_DATATYPE_INVALID = c_ulong(0)
SIMCONNECT_DATATYPE_INT32 = c_ulong(1)
SIMCONNECT_DATATYPE_INT64 = c_ulong(2)
SIMCONNECT_DATATYPE_FLOAT32 = c_ulong(3)
SIMCONNECT_DATATYPE_FLOAT64 = c_ulong(4)
SIMCONNECT_DATATYPE_STRING8 = c_ulong(5)
SIMCONNECT_DATATYPE_STRING32 = c_ulong(6)
SIMCONNECT_DATATYPE_STRING64 = c_ulong(7)
SIMCONNECT_DATATYPE_STRING128 = c_ulong(8)
SIMCONNECT_DATATYPE_STRING256 = c_ulong(9)
SIMCONNECT_DATATYPE_STRING260 = c_ulong(10)
SIMCONNECT_DATATYPE_STRINGV = c_ulong(11)

# SIMCONNECT_SIMOBJECT_TYPE
SIMCONNECT_SIMOBJECT_TYPE_USER = c_ulong(0)
SIMCONNECT_SIMOBJECT_TYPE_ALL = c_ulong(1)
SIMCONNECT_SIMOBJECT_TYPE_AIRCRAFT = c_ulong(2)

# SIMCONNECT_PERIOD
SIMCONNECT_PERIOD_NEVER = c_ulong(0)
SIMCONNECT_PERIOD_ONCE = c_ulong(1)
SIMCONNECT_PERIOD_VISUAL_FRAME = c_ulong(2)
SIMCONNECT_PERIOD_SIM_FRAME = c_ulong(3)
SIMCONNECT_PERIOD_SECOND = c_ulong(4)

# 默认参数用整型别名（函数签名默认值）
SIMCONNECT_PERIOD_SIM_FRAME_INT = int(SIMCONNECT_PERIOD_SIM_FRAME.value)
SIMCONNECT_DATATYPE_FLOAT64_INT = int(SIMCONNECT_DATATYPE_FLOAT64.value)
SIMCONNECT_DATATYPE_STRINGV_INT = int(SIMCONNECT_DATATYPE_STRINGV.value)

# SIMCONNECT_DATA_REQUEST_FLAG
SIMCONNECT_DATA_REQUEST_FLAG_DEFAULT = 0

# SIMCONNECT_EVENT_FLAG / GROUP_PRIORITY（SimConnect.h）
SIMCONNECT_GROUP_PRIORITY_HIGHEST = 0x19000000
SIMCONNECT_EVENT_FLAG_GROUPID_IS_PRIORITY = 0x00000010

# RequestDataOnSimObjectType 请求 ID 偏移（与 subscribe / get 共用）
TYPE_REQ_OFFSET = 50000
SIMCONNECT_RECV_ID_NULL = 0
SIMCONNECT_RECV_ID_EXCEPTION = 1
SIMCONNECT_RECV_ID_OPEN = 2
SIMCONNECT_RECV_ID_QUIT = 3
SIMCONNECT_RECV_ID_EVENT = 4

# 客户端事件 ID：SubscribeToSystemEvent("SimStart")
SIMCONNECT_CLIENT_EVENT_SIMSTART = 90001
SIMCONNECT_RECV_ID_EVENT_OBJECT_ADDREMOVE = 5
SIMCONNECT_RECV_ID_EVENT_FILENAME = 6
SIMCONNECT_RECV_ID_EVENT_FRAME = 7
SIMCONNECT_RECV_ID_SIMOBJECT_DATA = 8
SIMCONNECT_RECV_ID_SIMOBJECT_DATA_BYTYPE = 9
SIMCONNECT_RECV_ID_WEATHER_OBSERVATION = 10
SIMCONNECT_RECV_ID_CLOUD_STATE = 11
SIMCONNECT_RECV_ID_ASSIGNED_OBJECT_ID = 12
SIMCONNECT_RECV_ID_RESERVED_KEY = 13
SIMCONNECT_RECV_ID_CUSTOM_ACTION = 14
SIMCONNECT_RECV_ID_SYSTEM_STATE = 15
SIMCONNECT_RECV_ID_CLIENT_DATA = 16
SIMCONNECT_RECV_ID_EVENT_WEATHER_MODE = 17
SIMCONNECT_RECV_ID_EVENT_MULTIPLAYER_SERVER_STARTED = 22
SIMCONNECT_RECV_ID_EVENT_MULTIPLAYER_CLIENT_STARTED = 23
SIMCONNECT_RECV_ID_EVENT_MULTIPLAYER_SESSION_ENDED = 24
SIMCONNECT_RECV_ID_EVENT_RACE_END = 25
SIMCONNECT_RECV_ID_EVENT_RACE_LAP = 26

EXCEPTION_NAMES = {
    0: "NONE",
    1: "ERROR",
    2: "SIZE_MISMATCH",
    3: "UNRECOGNIZED_ID",
    4: "UNOPENED",
    5: "VERSION_MISMATCH",
    6: "TOO_MANY_GROUPS",
    7: "NAME_UNRECOGNIZED",
    8: "TOO_MANY_EVENT_NAMES",
}

HRESULT_NAMES = {
    0x80004005: "E_FAIL",
    0x80070005: "E_ACCESSDENIED",
    0x80070057: "E_INVALIDARG",
    0x80004001: "E_NOTIMPL",
    0x8000FFFF: "E_UNEXPECTED",
    0x800401F0: "CO_E_NOTINITIALIZED",
}

MSFS_EVENTS = {
    "THROTTLE_FULL",
    "THROTTLE_INCR",
    "THROTTLE_DECR",
    "THROTTLE_CUT",
    "MIXTURE_INCR",
    "MIXTURE_DECR",
    "PROP_PITCH_INCR",
    "PROP_PITCH_DECR",
    "AP_MASTER",
    "AP_PANEL_ALTITUDE_HOLD",
    "AP_PANEL_HEADING_HOLD",
    "AP_PANEL_SPEED_HOLD",
    "AP_PANEL_ATTITUDE_HOLD",
    "LANDING_LIGHTS_TOGGLE",
    "STROBES_TOGGLE",
    "BEACONS_TOGGLE",
    "NAV_LIGHTS_TOGGLE",
    "TAXI_LIGHTS_TOGGLE",
    "PANEL_LIGHTS_TOGGLE",
    "GEAR_TOGGLE",
    "PARKING_BRAKES",
    "SIM_RESET",
    "SITUATION_RESET",
    "REPAIR_AND_REFUEL",
    "TOGGLE_ENGINE",
    "TOGGLE_MASTER_IGNITION",
    "TOGGLE_ALTERNATOR",
    "TOGGLE_AVIONICS_MASTER",
    "VIEW_RESET",
    "EYEPOINT_RESET",
    "PAN_RESET",
    "FLAPS_INCR",
    "FLAPS_DECR",
    "FLAPS_UP",
    "FLAPS_DOWN",
    "ELEV_TRIM_UP",
    "ELEV_TRIM_DN",
    "AILERON_TRIM_LEFT",
    "AILERON_TRIM_RIGHT",
    "RUDDER_TRIM_LEFT",
    "RUDDER_TRIM_RIGHT",
}
